new branch, new file
toantd1202/Prometheus_new pull request #2
Opened 2020-04-07 01:30 UTC by toantd1202

2020-04-07 07:43 UTC, vtdat reviewed
ok rồi. sửa lại typo, format hơn 1 chút.

thêm 1 exporter nữa là cadvisor và vẽ lên grafana

2020-04-07 07:43 UTC, vtdat commented on configuration.md
> +![](https://github.com/toantd1202/buoc1/blob/master/Screenshot%20from%202020-04-01%2023-19-21.png?raw=true)
format

2020-04-07 07:43 UTC, vtdat commented on configuration.md
> +Optional for khiến Prometheus phải chờ trong một khoảng thời gian nhất định giữa lần đầu tiên gặp một phần tử vectơ đầu ra biểu thức mới và tính một cảnh báo là bắn cho phần tử này. Trong trường hợp
Option

2020-04-07 07:43 UTC, vtdat commented on configuration.md
> +## templating
Templating

2020-04-07 07:43 UTC, vtdat commented on configuration.md
> +#### cấu hình node exporter
Cấu hình

2020-04-09 07:16 UTC, vtdat requested changes
Đã test được gửi mail chưa?

2020-04-09 07:16 UTC, vtdat commented on configuration.md
> +![](https://github.com/toantd1202/buoc1/blob/master/Screenshot%20from%202020-03-31%2021-36-02.png?raw=true)
breakline

2020-04-09 07:16 UTC, vtdat commented on configuration.md
> +![](https://github.com/toantd1202/buoc1/blob/master/Screenshot%20from%202020-04-01%2010-00-55.png?raw=true)
breakline

2020-04-09 07:16 UTC, vtdat commented on configuration.md
> +
spacing gì nhiều tnay

2020-04-10 14:31 UTC, toantd1202 commented on configuration.md
> +![](https://github.com/toantd1202/buoc1/blob/master/Screenshot%20from%202020-03-31%2021-36-02.png?raw=true)
tada!!!

![Screenshot from 2020-04-10 21-17-07](https://user-images.githubusercontent.com/61723456/78998315-91279500-7b72-11ea-849f-c0ee78e43541.png)

2020-04-13 10:37 UTC, vtdat approved these changes
ok

2020-04-14 01:03 UTC, merged